### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by antasimakopoulos** [leonardocavagnis/SmartThermostat_AndroidAppBLE#1]
Hello Leonardo,

I am trying to run your android code on Android Studio 4.1.1 (attached pic.) and when I try to build the project I get the errors you can see on the attached picture. Can you please help?Unfortunately I do not have any experience in Android Studio.

Thank you in advance,
Antonis
![BLE example](https://user-images.githubusercontent.com/76622701/103154717-ffb08f80-47a1-11eb-9448-540fb8e92fb6.PNG)
![Android Version](https://user-images.githubusercontent.com/76622701/103154746-35557880-47a2-11eb-94db-e22eef92c762.PNG)
![Errors](https://user-images.githubusercontent.com/76622701/103154774-8e251100-47a2-11eb-93f0-a34834079f2b.PNG)

**Comment by Barros9** [comment]
Hi @antasimakopoulos, could you try to clean and rebuild project (Build menu -> Clean Project) and see what happens. Let me know.

**Comment by antasimakopoulos** [comment]
Hello, I tried to clean the project but the 3 errors remain. Any other ideas?

**Comment by Barros9** [comment]
Well, it's weird, I don't have problem building the project. Did you try to "invalidate and restart" (Click File-> Invalidate Caches/Restart -> Invalidate and Restart)? Also, if the problem remains could you share the screenshot of the first raw in Build Output (Look the pic)? 
![image](https://user-images.githubusercontent.com/16928777/103298213-2406a900-49fa-11eb-8789-a2f411316132.png)

**Comment by antasimakopoulos** [comment]
Thanks for the help. I managed to solve the build errors (followed automatic corrections suggestions). Now I have an other problem. It cannot be installed in the emulator (check attatched photo).
![Install error](https://user-images.githubusercontent.com/76622701/103300983-f1b07800-4a08-11eb-8355-85ac317625c3.PNG)
.

**Comment by Barros9** [comment]
Seems you have problem with your emulator, you could restart the emulator in cold boot (you can try wipe data too) or try a physical device.

![image](https://user-images.githubusercontent.com/16928777/103306283-81582580-4a0d-11eb-980d-9a352961a658.png)

**Comment by leonardocavagnis** [comment]
Hi Antonis,
it is not a problem related to this repository, I close this issue.
Thanks.
